export const GET_MARKET_PRICE = "GET_MARKET_PRICE";

export const ADD_USD_BALANCE = "ADD_USD_BALANCE";

export const SUBTRACT_USD_BALANCE = "SUBTRACT_USD_BALANCE";

export const ADD_BITCOIN_BALANCE = "ADD_BITCOIN_BALANCE";

export const SUBTRACT_BITCOIN_BALANCE = "SUBTRACT_BITCOIN_BALANCE";
